version: "3.8"

services:
  client:
    image: fc-retrieval-provider
    container_name: provider
    networks:
      - shared
    ports:
      - "${SERVICE_PORT}:80"
    env_file:
      - .env
     
networks:
  shared:
