name: Publish Docker image
on:
  pull_request:
    branches: [main]
env:
  docker_registry: docker.pkg.github.com
  docker_image_name: fc-retrieval-provider
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo Docker image tag
        run: echo "pr-${GITHUB_HEAD_REF:0:3}"
      - name: Build Docker image
        run: make build REGISTRY=$docker_registry/${{ github.repository }}/ VERSION="pr-${GITHUB_HEAD_REF:0:3}"
      - name: Push Docker image
        run: docker push $docker_registry/${{ github.repository }}/$docker_image_name:"pr-${GITHUB_HEAD_REF:0:3}"